// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkoinxznfehosaedgyoy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhrb2lueHpuZmVob3NhZWRneW95Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3MjUzMjAsImV4cCI6MjA1ODMwMTMyMH0.mssZ6k-fBe0fzoDxh9Qe-zQkK3o2H4W_AOKYOwG68Bg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);